services:
  company-research:
    build: .
    container_name: company-research-tool
    ports:
      - '8000:8000' # API Server
      - '8501:8501' # Web Interface
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount for persistent logs
      - ./logs:/app/logs
    networks:
      - company-research-network

networks:
  company-research-network:
    driver: bridge
